endpoints:
  enabled: true
  trace:
    enabled: false
  health:
    enabled: true
  info:
    enabled: true
  metrics:
    enabled: true

  cors.allowed-origins: http://localhost
  cors.allowed-methods: GET,POST

server.error.whitelabel.enabled: false

spring:
  graphql:
    graphiql:
      enabled: true
    websocket:
      path: /graphql

core:
  db: ${APP_DB:duckdb}
  duckdb:
    url: "jdbc:duckdb:/tmp/starter.db"
    init:
      file: "${DATASET_DIR:./db}/duckdb.sql"
      enabled: true

  pg:
    host: ${POSTGRES_HOST:localhost}
    port: ${POSTGRES_PORT:5432}
    username: ${POSTGRES_USER:starter_user}
    password: ${POSTGRES_PASSWORD:starter}
    database: ${POSTGRES_DB:starter}