endpoints:
  enabled: true
  trace:
    enabled: false
  health:
    enabled: true
  info:
    enabled: true
  metrics:
    enabled: true

  cors.allowed-origins: http://localhost
  cors.allowed-methods: GET,POST

server.error.whitelabel.enabled: false

spring:
  graphql:
    graphiql:
      enabled: true
    websocket:
      path: /graphql

core:
  db: duckdb
  duckdb:
    url: "jdbc:duckdb:/tmp/starter.db"
    init:
      file: "${DATASET_DIR:./db}/duckdb.sql"
      enabled: true

  pg:
    host: localhost
    port: 5432
    username: starter_user
    password: postgres
    database: starter