CREATE USER starter_owner WITH SUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT LOGIN NOREPLICATION NOBYPASSRLS;
GRANT starter_owner to postgres;
GRANT CONNECT,CREATE ON DATABASE starter TO starter_owner;

CREATE USER starter_user WITH NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT LOGIN NOREPLICATION NOBYPASSRLS;
GRANT starter_user to postgres;
GRANT CONNECT ON DATABASE starter TO starter_user;


CREATE SCHEMA app AUTHORIZATION starter_owner;

GRANT USAGE ON SCHEMA app TO starter_user;

GRANT SELECT,INSERT,UPDATE,DELETE ON ALL TABLES IN SCHEMA app TO starter_user;
GRANT SELECT,UPDATE ON ALL SEQUENCES IN SCHEMA app TO starter_user;
ALTER DEFAULT PRIVILEGES FOR ROLE starter_owner IN SCHEMA app GRANT SELECT,INSERT,UPDATE,DELETE ON TABLES TO starter_user;
ALTER DEFAULT PRIVILEGES FOR ROLE starter_owner IN SCHEMA app GRANT SELECT,UPDATE ON SEQUENCES TO starter_user;

ALTER ROLE starter_owner IN DATABASE starter SET search_path TO app,"$user",public;
ALTER ROLE starter_user IN DATABASE starter SET search_path TO app,"$user",public;

ALTER USER starter_owner WITH PASSWORD 'starter';
ALTER USER starter_user WITH PASSWORD 'starter';

set role starter_owner; 